### ISSUE TITLE
Deprecation of yt-dlp/homebrew-taps

### ISSUE THREAD

**Issue by Grub4K** [yt-dlp/homebrew-taps#10]
This repo is currently without a maintainer and due for deprecation:
- https://github.com/yt-dlp/yt-dlp/issues/8370

**Comment by pukkandan** [comment]
We should do https://github.com/orgs/Homebrew/discussions/3177 if possible

**Comment by bashonly** [comment]
d38e32b904125cba72a302ec30858866d0909cdc
