### ISSUE TITLE
no symlink in /opt/homebrew/bin to the yt-dlp binary

### ISSUE THREAD

**Issue by tgy** [yt-dlp/homebrew-taps#4]
there seems to be no symlink created to add the binary to `/opt/homebrew/bin`

had to do the following

```
cd /opt/homebrew/bin
ln -s ../Cellar/yt-dlp/2022.6.29/libexec/bin/yt-dlp yt-dlp
```

because otherwise the `yt-dlp` command is not added to the `PATH`

**Comment by Lesmiscore** [comment]
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4223
